version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elastic
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - myelastic
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200  # Changed to elastic instead of localhost
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=changeme
    networks:
      - myelastic

volumes:
  data01:
    driver: local

networks:
  myelastic:
    driver: bridge
